### ISSUE TITLE
I don't understand at all how to use this.  Docs don't provide examples.

### ISSUE THREAD

**Issue by Fuco1** [darkfeline/dantalian#12]
There's not a single example in the docs on how to invoke something.

Also nowhere is explained what `.dtags` is.

**Comment by darkfeline** [comment]
Sorry, the documentation is mostly technical, since I have yet to get around to writing a proper tutorial.  I suggest looking through the manpages if you haven't already.

A few examples off the top of my head:

    # Make a hard link, same as ln(1)
    $ dantalian link genre/rock/music.mp3 artist/billy-bob/music.mp3
    # but also works with directories
    $ dantalian link artist/billy-bob/album-folder genre/rock/album-folder

`dantalian unlink` is basically `rm` but it works properly with linked directories.

`dantalian rename`, again is basically `mv` but it works properly with linked directories.

`dantalian swap` is used for linked directories.  The way linked directories work is that there's one "real" directory and a bunch of symlinks pointing to it.  `dantalian swap` lets you swap the positions of the real directory and one of the symlinks.

`dantalian save` and `dantalian load` are for when you have changed linked directories without using Dantalian's commands, making Dantalian's metadata out of sync with the actual state of the filesystem.  You use them to sync the metadata state and the actual state back and forth.

`dantalian tag` and `dantalian untag` are just syntactic sugar versions of `link` and `unlink` for working with a "tagging" organization model.

Please ask if you have more questions, and I'll be happy to hear any suggestions you have.  Dantalian is sort of my playground for trying to figure out a satisfactory file organization solution.

**Comment by Fuco1** [comment]
I think my problem is that I don't understand the logic behind your scheme.  How/what metadata you store (and why), how is it then put on the disk etc.

If I do a bunch of `link`, what does it give me over just `ln`? Is the ability to consistently link directories the only advantage?

**Comment by darkfeline** [comment]
>Is the ability to consistently link directories the only advantage?

Currently, this is one of the main features, along with the syntactic sugar of the `tag` and `untag` commands.  At one point Dantalian offered FUSE support for mounting a "tagging" file system, which will be re-added at an indeterminate point in the future once I've figured out the best interface for it.

My logic is that after a lot of trial and error, hard linking is still the most versatile tool for organizing files, and Dantalian extends that for common file systems that lack directory linking with minimal overhead.  If that's too simple for you, I suggest taking a look at Tagsistant, which is very good.

>How/what metadata you store (and why), how is it then put on the disk etc.

Every linked directory has a `.dtags` file that contains the paths of that directory's links, one per line.  Most of Dantalian deals with the problem of keeping those files up to date with file system operations.

**Comment by Fuco1** [comment]
Thanks for the write up.

Actually, I'm mostly not interested at all at tagging directories, so that feature isn't the "seller" for me :) But I agree with your point that

> After a lot of trial and error, I believe that hard linking is still the most versatile tool for organizing files.

I thought long and hard about how to make tags work using hardlinks and symlinks and maybe I'll try to implement it some day, the problem of course is that mapping tags to hierarchy grows exponentially... ideally I would like a system with no fuse and no extra metadata.

I know about tagsistant and I even contributed couple ideas, the author is very receptive... but my gripes with it are impossible backuping and migration (as it is based on inodes and what not) plus the fact that the database is a very strong single-point-of-failure.  I am very wary to trust thousands of files to it and then lose it all.

**Comment by darkfeline** [comment]
What's wrong with making tags with hard links like:

    year/2015/picture.jpg
    place/yosemite/picture.jpg
    people/bob/picture.jpg

**Comment by Fuco1** [comment]
That's not really how I see tagging.  For example, if I tag something with `foo` and `bar` I want to be able to find it under `/foo/bar` as well as `/bar/foo`... but if you create all the permutations it quickly blows out of proportions (on a regular FS using e.g. symlinks)

I think of tags more like... narrowing, where it makes sense to start from whatever end and gradually get down to a managable subset of files.  I would ideally not want to think that "first I need to pick the genre, then the author, then the language" when I want to find a book... because this is practically no better than just having a tree.

How would I combine, in your scheme, query for "bob" in "yosemite"? Would it be `/people/bob/place/yosemite/` or the other way round?

**Comment by darkfeline** [comment]
Dantalian provides a robust search command for that:

    $ dantalian search AND people/bob place/yosemite END

Currently, this will be slow on really large sets of files, but I plan to add a caching feature to speed this up at an indeterminate point in the future.

Ideally, you would be able to do that search in the file system, but again, I'm still figuring out a good FUSE API.

What you propose (`/foo/bar` and `/bar/foo`) is utterly inconceivable without using FUSE.  The computer science simply doesn't work out.

>Ideally, I would like a system with no fuse and no extra metadata.

That's what I thought too, but your only choice would be to design a revolutionary new filesystem from scratch and get it accepted into the Linux kernel.

**Comment by ids1024** [comment]
Well, someone could write a kernel module, which would be the same performance and functionality wise as having it included in the kernel.

Hard links are much simpler though.

**Comment by darkfeline** [comment]
@ids1024 The hard part is designing the low level specifications for the file system, which is non-trivial, to make an understatement.

**Comment by ids1024** [comment]
@darkfeline I'm not seriously suggesting it, since writing actual filesystems is probably rather complicated. Hard links are a simple method, but perhaps more in line with the Unix philosophy and better as long as very high

**Comment by darkfeline** [comment]
>Hard links are a simple method, but perhaps more in line with the Unix philosophy and better as long as very high performance is not needed.

That's basically what Dantalian is doing in its current form.  I welcome any patches or suggestions however.
