### ISSUE TITLE
Windows / MacOs support

### ISSUE THREAD

**Issue by DeadlySquad13** [darkfeline/dantalian#16]
Hello!
I'm planning on integrating tags into my workflow and this project looks like a good solution! The only thing that bothers me is OS restrictions. Dantalian seems like a 100% Python app but, as far as I see in README, only Linux is supported. Do you have any plans on implementing Windows and MacOs compatibility? What parts should be changed to make this instrument cross-platform or it is not even possible?

Thanks for your effort building open-source tools!
Hope you'll give further insight on these questions. I'm trying to find a one-for-all solution for all my systems so I'm willing to help as much as I can if you provide some information.

**Comment by darkfeline** [comment]
I believe it works on OSX because OSX supports hard links.  I don't know about Windows, since hard links on Windows is weird.   If it doesn't work on Windows, I don't plan on making it work.  It should probably work on WSL.

**Comment by DeadlySquad13** [comment]
Thanks for quick response! Hard links is the only issue? I'll try it out then.
